/* Parent Try it preview: spoken heads-up, owl, Home back to settings, no real session changes. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium,webkit}=require('playwright'),root=path.resolve(__dirname,'..'),wk=process.argv.includes('--webkit');
const server=http.createServer((req,res)=>{const f=path.join(root,new URL(req.url,'http://local').pathname==='/'?'index.html':new URL(req.url,'http://local').pathname);
  if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);
  return res.end();}res.setHeader('Content-Type',f.endsWith('.html')?'text/html':f.endsWith('.json')?'application/json':f.endsWith('.mp3')?'audio/mpeg':'application/octet-stream');
  fs.createReadStream(f).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));
  const browser=await(wk?webkit:chromium).launch();try{for(const [width,height]of[[390,844],[844,390],[390,664]]){const c=await browser.newContext({viewport:{width,height},hasTouch:true,isMobile:true});
  await c.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));
  await c.route('https://fonts.gstatic.com/**',r=>r.abort());
  await c.route('**/assets/family/family.json',r=>r.fulfill({json:{contacts:[]}}));
  await c.addInitScript(()=>{localStorage.setItem('toyphone.settings',JSON.stringify({incoming:false,camera:'pretend',look:'drag',tilt:'off',play:15}));localStorage.setItem('toyphone.session',JSON.stringify({day:new Date().toDateString(),used:900000,ended:true}));});
  const p=await c.newPage(),errors=[];
  p.on('pageerror',e=>errors.push(e.message));
  const check=(ok,msg)=>{assert.ok(ok,msg);
  console.log('ok '+width+'x'+height+' '+msg);};
  await p.goto(`http://127.0.0.1:${server.address().port}/`);
  await p.waitForFunction(()=>window.__toyPhone);
  await p.evaluate(()=>{
    window.__previewFocus=[];
    for(const type of ['focusin','focusout','pointerdown','pointerup','touchend','click']){
      document.addEventListener(type,e=>{
        window.__previewFocus.push({type,target:e.target.id,active:document.activeElement?.id,time:Math.round(performance.now())});
        if(window.__previewFocus.length>30)window.__previewFocus.shift();
      },true);
    }
  });
  const hold=async()=>{await p.locator('#clock').focus();
  await p.keyboard.down('Enter');
  await p.locator('#settings').waitFor({state:'visible'});
  await p.keyboard.up('Enter');};
  const preview=async()=>{await p.locator('#testBreak').scrollIntoViewIfNeeded();
  await p.locator('#testBreak').focus();
  await p.keyboard.press('Enter');};
  const stored=()=>p.evaluate(()=>localStorage.getItem('toyphone.session'));
await hold();
  check(await p.locator('#testBreak').count()===1,'Try it offers the play-time preview');
  const before=await stored();
  await preview();
  await p.locator('#breakPreviewNotice').waitFor({state:'visible'});
  check(!(await p.locator('#settings').isVisible())&&!(await p.locator('#breakTime').isVisible()),'heads-up appears before the owl');
  check(await p.locator('#apps').evaluate(e=>e.inert)&&await p.locator('#homeBtn').evaluate(e=>e===document.activeElement),'preview blocks covered apps and focuses Home');
  await p.waitForFunction(()=>window.__toyPhone.voice().log.includes('Almost time for a break!'));
  await p.locator('#breakTime').waitFor({state:'visible',timeout:10000});
  await p.waitForFunction(()=>window.__toyPhone.voice().log.includes('Time for a break! See you soon!'));
  check(await stored()===before,'preview preserves the expired real session');
  await p.locator('#homeBtn').tap();
  await p.locator('#settings').waitFor({state:'visible'});
  check(await p.locator('#home').isVisible()&&await p.locator('#settings .sheet').evaluate(e=>e.scrollTop===0),'Home returns to settings at the home screen and top of sheet');
  await p.waitForFunction(()=>document.activeElement===document.getElementById('doneBtn'),null,{timeout:3000}).catch(async err=>{
    console.log('Preview focus events',await p.evaluate(()=>window.__previewFocus));throw err;
  });
  check(await p.locator('#doneBtn').evaluate(e=>e===document.activeElement),'returned settings has keyboard focus');
  await p.locator('#doneBtn').click();
  check(await p.locator('#breakTime').isVisible(),'closing settings preserves the real timeout lock');
await hold();
  await p.locator('#playReset').scrollIntoViewIfNeeded();
  await p.locator('#playReset').click();
  const reset=await stored(), usedBefore=await p.evaluate(()=>window.__toyPhone.session().used);
  await preview();
  await p.locator('#breakPreviewNotice').waitFor({state:'visible'});
  await p.locator('#homeBtn').tap();
  await p.locator('#settings').waitFor({state:'visible'});
  await p.waitForTimeout(6000);
  check(!(await p.locator('#breakTime').isVisible())&&!(await p.locator('#breakPreviewNotice').isVisible()),'Home during heads-up cancels pending owl');
  check(await stored()===reset,'canceling does not consume or reset play time');
await preview();
  await p.locator('#breakTime').waitFor({state:'visible',timeout:10000});
  await p.locator('#homeBtn').tap();
  await p.locator('#settings').waitFor({state:'visible'});
  check(await stored()===reset&&await p.evaluate(()=>window.__toyPhone.session().used)===usedBefore,'repeat preview neither consumes nor resets real play');
  await preview();
  await p.locator('#breakPreviewNotice').waitFor({state:'visible'});
  await p.evaluate(()=>window.dispatchEvent(new Event('pagehide')));
  await p.waitForTimeout(6000);
  check(!(await p.locator('#breakPreviewNotice').isVisible())&&!(await p.locator('#breakTime').isVisible()),'pagehide cancels preview and delayed owl');
  check(errors.length===0,'no JavaScript errors '+errors.join(';'));// An active grace period must survive a preview and its Home navigation.
await hold();
  await p.locator('#doneBtn').click();
  await p.evaluate(()=>window.__toyPhone.go('numsnack'));
  await p.evaluate(()=>window.__toyPhone.playTime(900000));
  await p.waitForFunction(()=>window.__toyPhone.session().ending);
  await hold();
  const grace=await stored(),usedGrace=await p.evaluate(()=>window.__toyPhone.session().used);
  await p.locator('[data-count="help"]').scrollIntoViewIfNeeded();
  await p.locator('[data-count="help"]').click();
  await preview();
  await p.locator('#breakTime').waitFor({state:'visible',timeout:10000});
  await p.locator('#homeBtn').tap();
  await p.locator('#settings').waitFor({state:'visible'});
  check(await stored()===grace&&await p.evaluate(()=>{const s=window.__toyPhone.session();
  return s.ending&&!s.ended;}),'changing count mode and previewing leaves the real grace period unfinished');
  check(await p.evaluate(()=>window.__toyPhone.session().used)===usedGrace,'grace-period preview consumes no play time');
  await p.locator('#doneBtn').click();
  await p.waitForFunction(()=>window.__toyPhone.session().ended,null,{timeout:7000});
  check(await p.locator('#breakTime').isVisible(),'real timeout still works after the preview');
await c.close();}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close());
