/* Optional pretend missions/cooperation and cancellation at completion boundaries. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium,webkit}=require('playwright');const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const rel=new URL(req.url,'http://localhost').pathname;const file=path.join(root,rel==='/'?'index.html':rel);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.html')?'text/html':file.endsWith('.js')?'text/javascript':'application/octet-stream');fs.createReadStream(file).pipe(res);});
(async()=>{fs.mkdirSync(path.join(__dirname,'screenshots'),{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await(process.argv.includes('--webkit')?webkit:chromium).launch();try{for(const [width,height] of [[390,844],[844,390],[390,664]]){const context=await browser.newContext({viewport:{width,height},hasTouch:true,isMobile:true});await context.addInitScript(()=>localStorage.setItem('toyphone.settings',JSON.stringify({incoming:false,camera:'pretend',tilt:'off'})));const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.waitForFunction(()=>window.__toyPhone);const go=n=>page.evaluate(n=>window.__toyPhone.go(n),n);const click=s=>page.locator(s).dispatchEvent('click',{detail:0});
await go('phone');await click('#contacts button:first-child');await page.waitForTimeout(5100);assert.equal(await page.locator('#friendMission').count(),1,'connected animal call offers a pretend mission');await click('#friendMission');await page.screenshot({path:`${__dirname}/screenshots/social-mission-${width}-${height}.png`});assert.ok(await page.locator('#missionReply').evaluate(el=>{const r=el.getBoundingClientRect();return r.width>=44&&r.height>=44&&r.bottom<=innerHeight&&r.left>=0;}),'mission reply fits screen');assert.equal(await page.locator('#missionReply').getAttribute('aria-label'),'Hello!');await click('#missionReply');await page.waitForTimeout(130);assert.equal(await page.locator('#missionReply').getAttribute('aria-label'),'I waved!');await click('#missionReplay');assert.equal(await page.locator('#missionReply').getAttribute('aria-label'),'I waved!');await click('#missionReply');await page.waitForTimeout(130);assert.equal(await page.locator('#missionReply').getAttribute('aria-label'),'Bye bye!');await click('#missionReply');await page.waitForTimeout(2100);assert.equal(await page.locator('#call').isHidden(),true);
await go('dinobuddies');await click('#dinobuddies [data-n="2"]');assert.equal(await page.locator('#dbTurns').count(),1,'optional turns available');await click('#dbTurns');await page.screenshot({path:`${__dirname}/screenshots/social-dino-${width}-${height}.png`});const left=page.locator('.db-side').first();await left.press('Enter');await page.waitForTimeout(850);assert.equal(await page.evaluate(()=>window.__toyPhone.dino().fill),1);assert.equal(await page.locator('.db-side').nth(1).getAttribute('data-turn'),'true');await left.press('Enter');await page.waitForTimeout(850);assert.equal(await page.evaluate(()=>window.__toyPhone.dino().fill),2,'helping either side never punished');await click('#dbReplay');assert.equal(await page.evaluate(()=>window.__toyPhone.dino().fill),2);
await go('paintpals');await click('#paintpals [data-n="1"]');await click('#ppPrompt');await page.screenshot({path:`${__dirname}/screenshots/social-paint-${width}-${height}.png`});assert.equal(await page.locator('#ppPrompt').getAttribute('aria-pressed'),'true');await page.locator('.pp-side').first().press('Enter');await page.waitForTimeout(500);assert.ok((await page.evaluate(()=>window.__toyPhone.paint().painted[0]))>0,'keyboard paints');
// Actual drawing finishes the picture; immediately leaving must settle the earned picture once.
await page.locator('.pp-side').first().evaluate(el=>{const r=el.querySelector('canvas').getBoundingClientRect();let id=100;for(let y=r.top;y<r.bottom;y+=5){el.dispatchEvent(new PointerEvent('pointerdown',{pointerId:id,clientX:r.left,clientY:y,bubbles:true}));el.dispatchEvent(new PointerEvent('pointermove',{pointerId:id,clientX:r.right,clientY:y,bubbles:true}));el.dispatchEvent(new PointerEvent('pointerup',{pointerId:id++,bubbles:true}));}});assert.equal(await page.evaluate(()=>window.__toyPhone.paint().done[0]),true);await go('home');const saved=await page.evaluate(()=>window.__toyPhone.paint());await page.waitForTimeout(1000);assert.deepEqual(await page.evaluate(()=>window.__toyPhone.paint()),saved,'completion does not run behind Home');await go('paintpals');await click('#paintpals [data-n="2"]');await page.waitForTimeout(2100);assert.equal(await page.evaluate(()=>window.__toyPhone.paint().rounds),saved.rounds,'old celebration cannot change new player mode');await click('#ppShelf');assert.equal(await page.locator('#ppShelfPanel').isVisible(),true);assert.ok(await page.locator('#ppShelfPictures button').count()>0,'completed painting survives interruption');await click('#ppShelfPictures button:first-child');assert.equal(await page.locator('#ppShelfPreview img').count(),1);await click('#ppShelfClose');
await go('snacktime');await page.waitForFunction(()=>window.__toyPhone.snack().want);const want=await page.evaluate(()=>window.__toyPhone.snack().want);await click(`[data-food="${want}"]`);await go('home');await go('snacktime');await page.waitForFunction(()=>window.__toyPhone.snack().want);assert.equal(await page.evaluate(()=>window.__toyPhone.snack().fed),0,'old bite cannot reward a new arrival');assert.deepEqual(errors,[]);console.log('Social play passed',width,height);await context.close();}}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
